### ISSUE TITLE
Enter edit mode bug

### ISSUE THREAD

**Issue by VimiummuimiV** [degarashi/ModernPrimitive#2]
After applying any modern primitive with Convert > Mesh, creating another primitive, and entering edit mode by pressing Tab without applying the new primitive, the previously applied primitive, which was removed before creating the new one, reappears as editable.
https://i.imgur.com/SdFmz2v.jpeg

**Comment by degarashi** [comment]
Thank you for the bug report.
I will get right on fixing it.

**Comment by degarashi** [comment]
fixed.
