### ISSUE TITLE
Default Cube dimensions are off

### ISSUE THREAD

**Issue by Thane5** [degarashi/ModernPrimitive#3]
The default cube is not a perfect cube, as you can see by these values of the Y axis:
![image](https://github.com/user-attachments/assets/7e99cb1b-1ba6-4be2-9bef-398dced5ad31)

**Comment by VimiummuimiV** [comment]
Confirm. The same issue on Y axis. Blender 4.3.2
https://i.imgur.com/AozUnta.jpeg

**Comment by degarashi** [comment]
The cube size issue has been fixed. Thanks for the report.
